routes:

  thread_default:
    route:          /thread/:thread_id/:action
    defaults:
      module:       default
      controller:   thread
      action:       index
    reqs:
      thread_id:     '[0-9]+'
  
  matsu_default:
    route:          /matsu/:thread_id/:action
    defaults:
      module:       default
      controller:   matsu
      action:       index
    reqs:
      thread_id:     'a|b|c'
 
  thread3_default:
    route:          /thread3/:genre_id/:action
    defaults:
      module:       default
      controller:   thread3
      action:       list
    reqs:
      thread_id:     '[0-9]+'
      
  entry3_default:
    route:          /entry3/:thread_id/:action
    defaults:
      module:       default
      controller:   entry3
      action:       list
    reqs:
      thread_id:     '[0-9]+'
  
 



#  sample:
#    route:          /:placeholder/:controller/:action
#    defaults:
#      module:       default
#      controller:   index
#      action:       index
#    reqs:
#      placeholder:     '[a-z]{2}'

#  regex_sample:
#    type:         Zend_Controller_Router_Route_Regex
#    route:        job-(\d+)/([^/]+)
#    defaults:
#      module:     default
#      controller: job
#    map:
#      1:          job_id
#      2:          action