model:        Bd_Orm_Main_Tag
page_name:    タグ
 
form:
  fields:
    id:
      settings:
        label: ID
    name:
      settings:
        label: 名称
 
list:
  delete_label:  削除
  method:        fetchAllNewOrdered
  display:
    - label:     ID
      column:    id
 
    - label:     タグ名
      column:    name